# NexT Alternate Theme Config
# Overrides theme settings without modifying the theme itself.

menu:
  home: / || fa fa-home
  about: /about/ || fa fa-user
  archives: /archives/ || fa fa-archive
  links: /links/ || fa fa-link
